carts/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('cart/', views.view, name="cart"),
    path('cart/remove/<int:id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/add/<int:food_id>/', views.add_to_cart, name='add_to_cart'),
    # path('cart/add/<int:food_id>/', views.add_to_cart, name='add_to_cart'),
] 

restaurants/urls.py
from django.urls import path, include
from .import views

urlpatterns = [
    path('', views.home, name="home"),
    path('restaurants/<slug>/', views.singlerestro, name='single_restaurant'),
    path('restaurants/', views.allrestros, name="restaurants"),

] 

restro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('carts.urls')),
    path('', include('restaurants.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from django.urls import reverse
from restaurants.models import Restaurant, Food
from django.contrib.auth.models import User



# Create your models here.

class CartItem(models.Model):
    cart = models.ForeignKey("Cart", on_delete=models.CASCADE)
    food = models.ForeignKey(Food, on_delete=models.CASCADE, default=0)
    quantity = models.IntegerField(default=0)
    line_total = models.DecimalField(default=10.99, max_digits=1000, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        try:
            return str(self.cart.id)
        except:
            return self.food.name

    def __str__(self):
        try:
            return str(self.cart.id)
        except:
            return self.food.name

    def augment_quantity(self, quantity):
        self.quantity = self.quantity + int(quantity)
        self.save()


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)


    # def __unicode__(self):
    #     return "Cart id: %s" %(self.id)


    def __str__(self):
        return "Cart id: %s" %(self.id)

restaurants/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Restaurant(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    pan_number = models.CharField(max_length=50)
    email = models.EmailField()
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    slug = models.SlugField(unique=True)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return str(self.name)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ('name', 'slug')

    def get_absolute_url(self):
        return reverse("single_restaurant", kwargs={"slug":self.slug})

class RestaurantImage(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, null=False, blank=False)
    image = models.ImageField(upload_to='restaurants/images/')



class Contact(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, null=False, blank=False)
    phone_num = models.CharField(max_length=15, null=True, blank=False)




class Food(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, null=False, blank=False)
    image = models.ImageField(upload_to='foods/images/')
    price = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)



    def __str__(self):
        return str(self.name) + "@" + self.restaurant.name

carts/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse
from .models import Cart, CartItem
from restaurants.models import Restaurant, Food
from django.contrib.auth.decorators import login_required


# Create your views here.

def view(request):
    try:
        the_id = request.session['cart_id']
        cart = Cart.objects.get(id=the_id)
    except:
        the_id = None
    if the_id:
        new_total = 0.00
        for item in cart.cartitem_set.all():
            line_total = float(item.food.price) * item.quantity
            new_total += line_total
        request.session['items_total'] = cart.cartitem_set.count()
        cart.total = new_total
        cart.save()
        context = {"cart": cart}
    else:
        empty_message = "Your Cart is Empty, please keep eating!!!!."
        context = {"empty": True, "empty_message":empty_message}
        
    template = "carts/view.html"
    return render(request, template, context)


def remove_from_cart(request, id):
    try:
        the_id = request.session['cart_id']
        cart = Cart.objects.get(id=the_id)
    except:
        return HttpResponseRedirect(reverse("cart"))

    cartitem = CartItem.objects.get(id=id)
    cartitem.delete()
    # cartitem.cart = None
    # cartitem.save()
    #send "success message"
    return HttpResponseRedirect(reverse("cart"))

# def get_cart_items(request):
#     return CartItem.objects.filter(cart_id=id(request))

def add_to_cart(request, food_id):
    request.session.set_expiry(120000)
    try:
        the_id = request.session['cart_id']

    except:
        new_cart = Cart()
        new_cart.save()
        request.session['cart_id'] = new_cart.id
        the_id = new_cart.id

    cart = Cart.objects.get(id=the_id)
    try:
        food = Food.objects.get(id=food_id)
    except Food.DoesNotExist:
        pass
    except:
        pass

    if request.method == "POST":
        quantity = request.POST['quantity']
        cart_item = CartItem.objects.create(cart=cart, food=food)
        if int(quantity) >= 1:
            cart_item.quantity = quantity
            cart_item.save()
            return HttpResponseRedirect(reverse("cart"))

    #send "error message"
    return HttpResponseRedirect(reverse("cart"))


# def add_to_cart(request, food_id):
#     try:
#         the_id = request.session['cart_id']
#         cart = Cart.objects.get(id=the_id)
#     except:
#         foods = Food.objects.get(id=food_id)
#         cart_foods = CartItem.objects.create(cart=cart, food=foods)
#         if request.method == "POST":
            
#             quantity = request.POST['quantity']
#             f = get_object_or_404(Food, id=foods)
#             # cart_foods = get_cart_items(request)
#             food_in_cart = False
#             for cart_item in cart_foods:
#                 if cart_item.food.id == f.id:
#                     cart_item.augment_quantity(quantity)
#                     food_in_cart = True
#                     return HttpResponseRedirect(reverse("cart"))
#             if not food_in_cart:
#                 ci = Cart()
#                 ci.food = f
#                 ci.quantity = quantity
#                 ci.cart_id = id(request)
#                 ci.save()
#                 return HttpResponseRedirect(reverse("cart"))

restaurants/views.py
from django.shortcuts import render, redirect, Http404, HttpResponseRedirect, get_object_or_404
from .models import Restaurant, RestaurantImage, Food
from django.urls import reverse


# Create your views here.

def home(request):
    restaurants = Restaurant.objects.all()
    context = {
        "restaurants":restaurants,
        }
    return render(request, 'home.html', context)

def allrestros(request):
    restaurants = Restaurant.objects.all()
    context = {'restaurants': restaurants}
    template = 'all.html'
    return render(request, template, context)


def singlerestro(request, slug):
    # try:
        restaurant = Restaurant.objects.get(slug=slug)
        foods = Food.objects.filter(restaurant=restaurant)
        images = RestaurantImage.objects.filter(restaurant=restaurant)
        context = {'restaurant': restaurant, 'images': images, 'foods':foods}
        template = 'restaurants/single.html'
        return render(request, template, context)

    # except:
    #     raise Http404

carts/templates/carts/view.html
{% extends 'base.html' %}

{% block content %}
<div class="col-sm-8 col-sm-offset-2"></div>

{% if empty %}

<h1 style="text-align: center;">{{ empty_message }}</h1>

{% else %}


<table class="table">
    <thead>
        <th>Item</th>
        <th>Qty</th>
        <th>Price</th>
    </thead>
    <tfoot>
        <tr>
            <td></td>
            <td></td>
            <td>Total: {{ cart.total }}</td>
        </tr>
    </tfoot>
    {% for item in cart.cartitem_set.all %}
    <tr>
        <td>{{ item.food }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.food.price }}</td>
        <td><a href="{% url 'remove_from_cart' item.id %}">Remove</a></td>
    </tr>
    {% endfor %}
</table>
<br>
<a href="#">Checkout</a>

{% endif %}
</div>

{% endblock %}

restaurants/templates/restaurants/allfoods.html
{% extends 'base.html' %}


{% block content %}

<div class="row">

  
    {% for food in foods %}
        <div class="col-sm-4">
          <div class="thumbnail">
            
              <img class="img-responsive" src="{{ MEDIA_URL }} {{ food.image.url }}"/>

          <div class="caption">
            <h3>{{ food.name }}</h3></a>
            <p>{{ food.description}}</p>
            <p>Price: Rs {{ food.price}}</p>
          </div>
        </div> 
        </div>
        {% endfor %}


  {% cycle "" "" "</div><br><hr><div class='row'>" %}


</div>
{% endblock %}

restaurants/templates/restaurants/single.html
{% extends 'base.html' %}


{% block content %}

<div class="row">
    <div class="col-sm-4">

        {% for img in images %}
        <div class="col-xs-12">
            <img src="{{MEDIA_URL}}{{ img.image.url }}" class='img-thumbnail' alt="">
            
            <hr>
        </div>
        {% endfor %}
        <h1>{{ restaurant.name }}</h1>
        <h4>{{ restaurant.description }}</h4>
        <hr>
        
                           
        <h1>Menu</h1>
        <div class="col-xs-6">
            {% for food in foods %}
                <a href="#" class="thumbnail">
                    <img class='img-responsive' src="{{ MEDIA_URL }}{{ food.image.url }}" />
                    <h4>{{item.name}}</h4>
                </a>
            
            <form class="form pull-right" method="POST" action="{% url 'add_to_cart' food.id %}">
                {% csrf_token %}
                <input type="number" name="quantity" value="1">   
                <input class="btn btn-default"  type="submit" value="Add to menu">
            </form>
           
            Price: {{ food.price }} <br>
            {{ food.description|linebreaks}}
          
            <br>
            <br>
            
            {% endfor %}
        
        </div>
        
        

    </div>
    
</div>
{% endblock %}

restro/templates/all.html
{% extends 'base.html' %}


{% block content %}

<div class="row">
  
    {% for restaurant in restaurants %}
        <div class="col-sm-4">
          <div class="thumbnail">
  
          {% for item in restaurant.restaurantimage_set.all %}
          
          
            
              <img class="img-responsive"src="{{ MEDIA_URL }} {{ item.image.url }}"/>
              <!-- {% if item.featured %} -->
            <!-- {% endif %} -->
          {% endfor %}
          <div class="caption">
          <a href="{{ restaurant.get_absolute_url }}"><h3>{{ restaurant.name }}</h3></a>
            <p>{{ restaurant.description}}</p>
            <p><a href="{{ restaurant.get_absolute_url }}" class="btn btn-primary" role="button">View</a><a href="#" class="btn btn-default" role="button">Button</a></p>
          </div>
        </div>
          

        </div>

  {% cycle "" "" "</div><br><hr><div class='row'>" %}

  {% endfor %}

</div>
{% endblock %}

restro/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.3/examples/navbar-fixed-top/">

    <title>{% block head_title %}{% endblock %}RESTRO</title>

    {% load static %}
    <!-- <link rel='stylesheet' href='{% static "css/bootstrap.min.css" %}'/>
    <link rel='stylesheet' href='{% static "css/bootstrap-theme.min.css" %}'/> -->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="https://getbootstrap.com/docs/3.3/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/3.3/examples/navbar-fixed-top/navbar-fixed-top.css" rel="stylesheet">

    <style>


      {% block styles %}
      {% endblock %}


      .background_img_thumb {
        width:100%;
        height:100%;
        background-image: url("{% static "img/placeholder.svg" %}");
        background-size:cover;
        background-repeat:no-repeat;
        background-position:center;
       
      }
    </style>
    

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="https://getbootstrap.com/docs/3.3/assets/js/ie-emulation-modes-warning.js"></script>


  </head>

  <body>

    {% include 'navbar.html' %}

    
      {% block jumbotron %}
      {% endblock %}
 

      <div class="container">
        <!-- {% if messages %}
        {% for message in messages %}
          <div class="alert {% if 'sucess' in message.tags %} alert-success{% elif 'warning' in message.tags %}alert-warning{% elif 'error' in message.tags %}alert-danger{% endif %} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            {% if "safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
          </div>
          {% endfor %}
        {% endif %} -->
      {% block content %}
      {% endblock %}

      </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

  </body>
</html>

restro/templates/home.html
{% extends 'base.html' %}
{% block head_title %}
Welcome to
{% endblock %}

{% block styles %}
  .jumbotron{
    <!-- color: red; -->
  }
{% endblock %}

{% block jquery %}
<!-- alert("Welcome!"); -->
{% endblock %}

{# Comments here #}

{% block jumbotron2 %}
<!-- Main component for a primary marketing message or call to action -->
<div class="container">
<div class="jumbotron">
  <h1>Hello {{ username_is }}</h1>
  <p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
  <p>To see the difference between static and fixed top navbars, just scroll.</p>
  <p>
    <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
  </p>
</div>
</div>

{% endblock %}


{% block content %}

<div class="row">
  
    {% for restaurant in restaurants %}
        <div class="col-sm-4">
          <div class="thumbnail">
  
          {% for item in restaurant.restaurantimage_set.all %}
          
          
          <a href="{{ restaurant.get_absolute_url }}">  
              <img class="img-responsive" src="{{ MEDIA_URL }} {{ item.image.url }}"/>
          </a>
              <!-- {% if item.featured %} -->
            <!-- {% endif %} -->
          {% endfor %}
          <div class="caption">
          <a href="{{ restaurant.get_absolute_url }}"><h3>{{ restaurant.name }}</h3></a>
            <p>{{ restaurant.description|truncatewords:15}}</p>
            <p><a href="{{ restaurant.get_absolute_url }}" class="btn btn-primary" role="button">View</a><a href="#" class="btn btn-default" role="button">Button</a></p>
          </div>
        </div>
          

        </div>

  {% cycle "" "" "</div><br><hr><div class='row'>" %}

  {% endfor %}

</div>
{% endblock %}

restro/templates/navbar.html
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">RESTRO</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" action="/s/">
              <div class="form-group">
                <input type="text" class="form-control" name="q" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
              <li class=""><a href="{% url 'restaurants' %}">Restaurants</a></li>
              <li class=""><a href="#">Foods</a></li>
              <li><a href="{% url 'cart' %}">Cart <span class="badge">{% if not request.session.items_total %} 0 {% else %} {{ request.session.items_total }} {% endif %}</span></a></li>
              {% if request.user.is_authenticated %}
              <li class=""><a href="#">Account</a></li>
              <li class=""><a href="#">Logout</a></li>
            {% else %}
              <li class=""><a href="#">Register</a></li>
              <li class=""><a href="#">Login</a></li>
            {% endif %}
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>